

    
export enum actionType {
   
    LOADING  = "LOADING" ,
    LOADING2  = "LOADING2" ,
    IS_DATA_SUCCESS  = "IS_DATA_SUCCESS" ,
    LOADING_PAGE  = "LOADING_PAGE" ,
    ALERT_MESSAGE  = "ALERT_MESSAGE" ,
}
export enum cartActionType {
    ADD_CART = "ADD_CART",
    DELETE ="DELETE_CART" ,
    CARTS = "CARTS",
    CART = "CART",
    }


    
export enum categoryActionType {
    ADD_CATEGORY  = "ADD_CATEGORY" ,
    UPDATE_CATEGORY  = "UPDATE_CATEGORY" ,
    DELETE_CATEGORY  = "DELETE_CATEGORY" ,
    ADMIN_CATEGORIES  = "ADMIN_CATEGORIES" ,
    ADMIN_CATEGORIES2  = "ADMIN_CATEGORIES2" ,
    ADMIN_CATEGORIES3  = "ADMIN_CATEGORIES3" ,
    USER_CATEGORIES  = "USER_CATEGORIES" ,
    CATEGORY = "CATEGORY" ,
    LOADING  = "LOADING" ,
}

export enum commentActionType {
    ADD_COMMENT="ADD_COMMENT",
    DELETE_COMMENT="DELETE_COMMENT",
    ADMIN_COMMENTS="ADMIN_COMMENTS",
    USER_COMMENTS="USER_COMMENTS",
}


export enum orderActionType {
    ADD_ORDER = "ADD_ORDER",
    DELETE_ORDER = "DELETE_ORDER",
    ADMIN_ORDERS = "ADMIN_ORDERS",
    USER_ORDERS = "USER_ORDERS",
}

export enum bannerActionType {
    ADD_BANNER = "ADD_BANNER",
    UPDATE_BANNER = "UPDATE_BANNER",
    DELETE_BANNER = "DELETE_BANNER",
    ADMIN_BANNERS = "ADMIN_BANNERS",
    USER_BANNERS= "USER_BANNERS",
    BANNER= "BANNER",
}

export enum colorActionType {
    ADD_COLOR = "ADD_COLOR",
    UPDATE_COLOR = "UPDATE_COLOR",
    DELETE_COLOR = "DELETE_COLOR",
    ADMIN_COLORS = "ADMIN_COLORS",
    USER_COLORS= "USER_COLORS",
    COLOR= "COLOR",
}

export enum brandActionType {
    ADD_BRAND = "ADD_BRAND",
    UPDATE_BRAND = "UPDATE_BRAND",
    DELETE_BRAND = "DELETE_BRAND",
    ADMIN_BRANDS = "ADMIN_BRANDS",
    USER_BRANDS= "USER_BRANDS",
    BRAND= "BRAND",
}
export enum settingActionType {
    ADD_SETTING = "ADD_SETTING",
    UPDATE_SETTING = "UPDATE_SETTING",
    DELETE_SETTING = "DELETE_SETTING",
    ADMIN_SETTINGS = "ADMIN_SETTINGS",
    USER_SETTINGS= "USER_SETTINGS",
    SETTING= "SETTING",
}

export enum roleActionType {
    ADD_ROLE = "ADD_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
    ADMIN_ROLES = "ADMIN_ROLES",
    USER_ROLES= "USER_ROLES",
    ROLE= "ROLE",
}
export enum permissionActionType {
    ADD_PERMISSION = "ADD_PERMISSION",
    UPDATE_PERMISSION = "UPDATE_PERMISSION",
    DELETE_PERMISSION = "DELETE_PERMISSION",
    ADMIN_PERMISSIONS = "ADMIN_PERMISSIONS",
    USER_PERMISSIONS= "USER_PERMISSIONS",
    PERMISSION= "PERMISSION",
}
export enum sizeActionType {
    ADD_SIZE = "ADD_SIZE",
    UPDATE_SIZE = "UPDATE_SIZE",
    DELETE_SIZE = "DELETE_SIZE",
    ADMIN_SIZES = "ADMIN_SIZES",
    USER_SIZES= "USER_SIZES",
    SIZE= "SIZE",
}
export enum productActionType {
    ADD_PRODUCT = "ADD_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    ADMIN_PRODUCTS = "ADMIN_PRODUCTS",
    USER_PRODUCTS = "USER_PRODUCTS",
    ADMIN_PRODUCT = "ADMIN_PRODUCT",
    USER_PRODUCT = "USER_PRODUCT",
}

export enum featureActionType {
    ADD_FEATURE = "ADD_FEATURE",
    UPDATE_FEATURE = "UPDATE_FEATURE",
    DELETE_FEATURE = "DELETE_FEATURE",
    ADMIN_FEATURES = "ADMIN_FEATURES",
    USER_FEATURES= "USER_FEATURES",
    FEATURE= "FEATURE",
}
export enum detailActionType {
    ADD_DETAIL = "ADD_DETAIL",
    UPDATE_DETAIL = "UPDATE_DETAIL",
    DELETE_DETAIL = "DELETE_DETAIL",
    ADMIN_DETAILS = "ADMIN_DETAILS",
    USER_DETAILS= "USER_DETAILS",
    DETAIL= "DETAIL",
}

export enum userActionType {
    USER_LOGIN = "USER_LOGIN",
    USER_REGISTER = "USER_REGISTER",
    USER_INFO = "USER_INFO",
    
}
